<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table, th, td, tr{
            border: 1 px solid rgba(16, 173, 134, 0.699);
        }
    
    
    </style>
</head>
<body>
    <table>
        <tr>
            <th>Pared</th>
            <th>ENTRADA</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>Pared</th>
            <th>ENTRADA</th>
            <th>Pared</th>

        </tr>
        <tr>
            <td>Pared</td>
            <td>Disponible</td>
            <td>Vía</td>
        </tr>
    </table>
</body>
</html>
